version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/build

hooks:
  BeforeInstall:
    - location: scripts/server_clear.sh
      timeout: 3000
      runas: root
  AfterInstall:
    - location: scripts/initialize.sh
      timeout: 3000
      runas: root
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 3000
      runas: root
  ValidateService:
    - location: scripts/server_validate.sh
      timeout: 3000
      runas: root
