FROM nginx:latest

ARG DOMAIN_NAME

RUN mkdir /var/log/nginx/proxy
RUN touch /var/log/nginx/proxy/access.log
RUN touch /var/log/nginx/proxy/error.log

RUN mkdir /etc/nginx/sites-available
RUN mkdir /etc/nginx/sites-enabled

COPY ./data/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./data/nginx/conf.d /etc/nginx/conf.d
COPY ./data/nginx/sites-available /etc/nginx/sites-available

RUN ln -s /etc/nginx/sites-available/${DOMAIN_NAME} /etc/nginx/sites-enabled
