INSERT INTO CATEGORIES(CATEGORY_NAME) VALUES ('헬스');
INSERT INTO CATEGORIES(CATEGORY_NAME) VALUES ('크로스핏');
INSERT INTO CATEGORIES(CATEGORY_NAME) VALUES ('요가');
INSERT INTO CATEGORIES(CATEGORY_NAME) VALUES ('필라테스');
INSERT INTO CATEGORIES(CATEGORY_NAME) VALUES ('오운완');
INSERT INTO CATEGORIES(CATEGORY_NAME) VALUES ('오늘의 식단');
