= REST Docs
:toc: left
:toclevels: 2
:toc-title: APIs
:doctype: book
:icons: font
:docinfo: shared-head
:sectlinks:
:source-highlighter: highlightjs

[[introduction]]
== 소개
Helfit API Documents

[[common]]
== 공통 사항

=== Domain

|===
| 환경 | domain

| 개발서버
| `localhost:8080/api/*`

| 운영서버
| `https://back.helfit.life/api/*`
|===

=== HTTP State Code

|===
| Code | Description

| `200 OK`
| 요청을 성공적으로 처리함.

| `201 Created`
| 새 리소스를 성공적으로 생성.
응답 헤더 `Location` 해당 리소스의 URI 생성됨.

| `204 No Content`
| 기존 리소스를 성공적으로 반영.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우.

| `404 Not Found`
| 요청한 리소스가 없음.

| `401 Unauthorized`
| 요청한 리소스를 처리 할 권한이 없음.

| `403 Access Denied`
| 권한 또는 토큰 인증 오류로 인한 접근 거부.

| `405 Method Not Allowed`
| 지원하지않는 메소드로 요청을 보낸 경우.

| `406 Not Acceptable`
| 잘못된 양식으로 요청을 보낸 경우.

|`500 Internal Server Error`
| 서버 오류로 인한 요청 처리 실패시.
|===

[[APIs]]

== Users
=== 회원가입
operation::user-controller-test/signup-test[]
=== 회원 로그인
operation::user-controller-test/login-test[]
=== 회원 토큰 재발급
operation::user-controller-test/refresh-token-test[snippets='curl-request,http-request,http-response,response-fields-body']
=== 회원 이메일 인증
operation::user-controller-test/confirm-email-test[snippets='curl-request,http-request,request-parameters']
=== 회원 이메일 인증 재발송
operation::user-controller-test/resend-confirm-email-test[snippets='curl-request,http-request,http-response']
=== 회원 정보 조회
operation::user-controller-test/get-user-test[snippets='curl-request,http-request,http-response,response-body,response-fields-header,response-fields-data']
=== 회원 정보 수정
operation::user-controller-test/update-user-test[snippets='curl-request,http-request,http-response,response-body,response-fields-header,response-fields-data']
=== 회원 비밀번호 변경
operation::user-controller-test/update-user-password-test[snippets='curl-request,custom-request-fields,http-request,request-body,response-body']
=== 회원 이미지 등록 & 수정
operation::user-controller-test/update-user-profile-image-test[snippets='curl-request,http-request,request-parts,response-body,response-fields-body']
=== 회원 이미지 삭제
operation::user-controller-test/delete-user-profile-image-test[snippets='curl-request,http-request,http-response,response-body']
=== 회원 탈퇴
operation::user-controller-test/withdraw-user-test[snippets='curl-request,http-request,http-response,request-body,response-body']

== Calendar
=== 캘린더 등록
operation::calendar-controller-test/post-calendar-test[snippets='curl-request,custom-request-fields,http-request,http-response,request-body,response-body']
=== 캘린더 개별 검색
operation::calendar-controller-test/get-calendar-test[snippets='curl-request,httpie-request,http-request,http-response,path-parameters,response-body,response-fields-data,response-fields-header']
=== 캘린더 등록일 기준 검색
operation::calendar-controller-test/get-calendar-test[snippets='curl-request,httpie-request,http-request,http-response,request-parameters,response-body,response-fields-data,response-fields-header']
=== 캘린더 수정
operation::calendar-controller-test/update-calendar-test[snippets='curl-request,custom-request-fields,httpie-request,http-request,http-response,request-body,response-body,response-fields-data,response-fields-header']
=== 캘린더 수정
operation::calendar-controller-test/delete-calendar-test[snippets='curl-request,http-request,http-response,request-body,response-body']


== Calculator
=== 계산기 결과 생성
operation::calculator-controller-test/post-result-test[]
=== 계산기 결과 조회
operation::calculator-controller-test/get-result-test[]
=== 계산기 결과 수정
operation::calculator-controller-test/patch-result-test[]
=== 계산기 결과 삭제
operation::calculator-controller-test/delete-result-test[]

== Statistics
=== 칼로리, 생성일자 조회
operation::stat-controller-test/get-board-stat-test[]
=== 오운완 게시판 최근게시물 3개 조회
operation::stat-controller-test/get-kcal-stat-test[]
=== 사용자의 최근 몸무게 수정 조회
operation::stat-controller-test/get-weight-stat-test[]
