= REST Docs
:toc: left
:toclevels: 2
:toc-title: APIs
:doctype: book
:icons: font
:docinfo: shared-head
:sectlinks:
:source-highlighter: highlightjs

[[introduction]]
== 소개
Helfit API Documents

[[common]]
== 공통 사항

=== Domain

|===
| 환경 | domain

| 개발서버
| `localhost:8080/api/*`

| 운영서버
| `https://back.helfit.life/api/*`
|===

=== HTTP State Code

|===
| Code | Description

| `200 OK`
| 요청을 성공적으로 처리함.

| `201 Created`
| 새 리소스를 성공적으로 생성.
응답 헤더 `Location` 해당 리소스의 URI 생성됨.

| `204 No Content`
| 기존 리소스를 성공적으로 반영.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우.

| `404 Not Found`
| 요청한 리소스가 없음.

| `401 Unauthorized`
| 요청한 리소스를 처리 할 권한이 없음.

|`500 Internal Server Error`
| 요청한 리소스 처리 실패 서버 오류.
|===

[[APIs]]

== Users
=== 회원가입
operation::user-controller-test/signup-test[]
=== 회원정보 조회
operation::user-controller-test/get-user-test[snippets='curl-request,http-request,http-response,response-body,response-fields-header,response-fields-data']
=== 계산기 결과 생성
operation::calculator-controller-test/post-result-test[]
=== 계산기 결과 조회
operation::calculator-controller-test/get-result-test[]
=== 계산기 결과 수정
operation::calculator-controller-test/patch-result-test[]
=== 계산기 결과 삭제
operation::calculator-controller-test/delete-result-test[]
=== 칼로리, 생성일자 조회
operation::stat-controller-test/get-board-stat-test[]
=== 오운완 게시판 최근게시물 3개 조회
operation::stat-controller-test/get-kcal-stat-test[]
=== 사용자의 최근 몸무게 수정 조회
operation::stat-controller-test/get-weight-stat-test[]