spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080

management:
  server:
    port: 8082

---

spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081

management:
  server:
    port: 8083
