domain:
  front: https://www.helfit.life
  back: https://back.helfit.life

app:
  auth:
    tokenSecret: ${JWT_SECRET_KEY}
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedSuccessRedirectUris:
      - https://www.helfit.life/oauth2.html
    authorizedFailRedirectUris:
      - https://www.helfit.life/404.html

logging:
  level:
    org.hibernate.SQL: trace

spring:
  profiles:
    include:
      - common
      - dev
  redis:
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
    port: 6379
    host: redis
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath*:db/mysql/data.sql
      # schema-locations: classpath*:db/mysql/schema.sql
